name: Aymerick's stuff
url: http://www.aymerick.com
description: The personal website of a generalist developer living in France.
author: Aymerick Jéhanne

rss_post_limit: 20

markdown: redcarpet
highlighter: pygments

exclude:
  - "bower_components"
  - "node_modules"
  - ".gitignore"
  - "bower.json"
  - "Gemfile"
  - "Gemfile.lock"
  - "Gruntfile.coffee"
  - "LICENSE"
  - "package.json"
  - "Rakefile"
  - "README.md"

include:
  - .nojekyll
